 language: node_js
  node_js:
    - "node"
  cache: npm
  script: npm run build
  deploy:
    provider: pages
    skip_cleanup: true
    github_token: f864d33aff7793f9ac49c0876833575655c548f9
    local_dir: dist
    on:
      branch: master